### ISSUE TITLE
Resolve placeholders eagerly

### ISSUE THREAD

**Issue by ehp246** [ehp246/auf-jms#116]
java.lang.IllegalArgumentException: Could not resolve placeholder 'xtdforce.xf-server.jms.destination.newScreeningEvent' in value "${xtdforce.xf-server.jms.destination.newScreeningEvent}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:180)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)

**Comment by ehp246** [comment]
Merged to master.
