### ISSUE TITLE
Support Enum on String properties

### ISSUE THREAD

**Issue by ehp246** [ehp246/auf-jms#129]
java.lang.RuntimeException: Un-supported property type com.fadv.xtdforce.mailer.jms.inbox.EmailType
	at me.ehp246.aufjms.core.util.TextJmsMsg.property(TextJmsMsg.java:106) ~[auf-jms-0.8.1.jar:?]
	at me.ehp246.aufjms.core.endpoint.DefaultInvocableBinder.bindContextArgs(DefaultInvocableBinder.java:149) ~[auf-jms-0.8.1.jar:?]

**Comment by ehp246** [comment]
In 0.8.2.
