### ISSUE TITLE
@OfProperty should support Parameter Name on dispatch and inbound

### ISSUE THREAD

**Issue by ehp246** [ehp246/auf-jms#151]
java.lang.IllegalArgumentException: Property name must not be the empty string
	at org.apache.qpid.jms.message.JmsMessagePropertySupport.checkPropertyNameIsValid(JmsMessagePropertySupport.java:59) ~[qpid-jms-client-0.53.0.jar:?]
	at org.apache.qpid.jms.message.JmsMessagePropertyIntercepter.getProperty(JmsMessagePropertyIntercepter.java:692) ~[qpid-jms-client-0.53.0.jar:?]
	at org.apache.qpid.jms.message.JmsMessage.getObjectProperty(JmsMessage.java:353) ~[qpid-jms-client-0.53.0.jar:?]
	at org.apache.qpid.jms.message.JmsMessage.getStringProperty(JmsMessage.java:393) ~[qpid-jms-client-0.53.0.jar:?]
	at me.ehp246.aufjms.core.util.TextJmsMsg.lambda$property$5(TextJmsMsg.java:99) ~[auf-jms-0.8.6.jar:?]
	at me.ehp246.aufjms.api.jms.JMSSupplier.invoke(JMSSupplier.java:17) ~[auf-jms-0.8.6.jar:?]
	at me.ehp246.aufjms.core.util.TextJmsMsg.property(TextJmsMsg.java:99) ~[auf-jms-0.8.6.jar:?]
	at me.ehp246.aufjms.core.endpoint.DefaultInvocableBinder.bindContextArgs(DefaultInvocableBinder.java:153) ~[auf-jms-0.8.6.jar:?]
	at me.ehp246.aufjms.core.endpoint.DefaultInvocableBinder.bind(DefaultInvocableBinder.java:67) ~[auf-jms-0.8.6.jar:?]
	at me.ehp246.aufjms.core.endpoint.InvocableDispatcher$1.run(InvocableDispatcher.java:91) ~[auf-jms-0.8.6.jar:?]
	at me.ehp246.aufjms.core.endpoint.InvocableDispatcher.dispatch(InvocableDispatcher.java:59) ~[auf-jms-0.8.6.jar:?]
	at me.ehp246.aufjms.core.endpoint.InboundEndpointListenerConfigurer$1$1.onMessage(InboundEndpointListenerConfigurer.java:146) ~[auf-jms-0.8.6.jar:?]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736) ~[spring-jms-5.3.23.jar:5.3.23]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696) ~[spring-jms-5.3.23.jar:5.3.23]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) ~[spring-jms-5.3.23.jar:5.3.23]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:331) ~[spring-jms-5.3.23.jar:5.3.23]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:270) ~[spring-jms-5.3.23.jar:5.3.23]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1237) ~[spring-jms-5.3.23.jar:5.3.23]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1227) ~[spring-jms-5.3.23.jar:5.3.23]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1120) ~[spring-jms-5.3.23.jar:5.3.23]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by ehp246** [comment]
In v0.8.7.
