### ISSUE TITLE
Review Null exception on @OfProperty

### ISSUE THREAD

**Issue by ehp246** [ehp246/auf-jms#220]
```
java.lang.NumberFormatException: property Arg1 was null
	at org.apache.qpid.jms.message.JmsMessagePropertySupport.convertPropertyTo(JmsMessagePropertySupport.java:39) ~[qpid-jms-client-2.0.0.jar:?]
	at org.apache.qpid.jms.message.JmsMessage.getIntProperty(JmsMessage.java:373) ~[qpid-jms-client-2.0.0.jar:?]
	at me.ehp246.aufjms.core.util.TextJmsMsg.lambda$property$6(TextJmsMsg.java:101) ~[auf-jms-2.2.2.jar:?]
	at me.ehp246.aufjms.api.jms.JMSSupplier.invoke(JMSSupplier.java:17) ~[auf-jms-2.2.2.jar:?]
	at me.ehp246.aufjms.core.util.TextJmsMsg.property(TextJmsMsg.java:101) ~[auf-jms-2.2.2.jar:?]
	at me.ehp246.aufjms.core.inbound.DefaultInvocableBinder.lambda$parse$11(DefaultInvocableBinder.java:137) ~[auf-jms-2.2.2.jar:?]
```

**Comment by ehp246** [comment]
Pushed
