### ISSUE TITLE
Unit Test failure at CompletedInvocationTest on MacOS Sonoma 14.4 (M1 Pro)

### ISSUE THREAD

**Issue by mingfuqin** [ehp246/auf-jms#251]
[WARNING] Tests run: 2, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0 s -- in me.ehp246.test.embedded.reply.ReplyTest
[INFO] Running me.ehp246.test.embedded.inbound.completed.CompletedInvocationTest
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.101 s <<< FAILURE! -- in me.ehp246.test.embedded.inbound.completed.CompletedInvocationTest
[ERROR] me.ehp246.test.embedded.inbound.completed.CompletedInvocationTest.completed_01 -- Time elapsed: 0.007 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: but was:
at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1145)
at me.ehp246.test.embedded.inbound.completed.CompletedInvocationTest.completed_01(CompletedInvocationTest.java:52)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)

**Comment by mingfuqin** [comment]
Duplicate issue of 252.
